FILTER_IDS:
  - ["Stromerzeugung: Braunkohle", 1223]
  - ["Stromerzeugung: Kernenergie", 1224]
  - ["Stromerzeugung: Wind Offshore", 1225]
  - ["Stromverbrauch: Gesamt (Netzlast)", 410]
REGIONS:
  - "DE"
  - "AT"
  - "LU"
  - "Amprion"
RESOLUTIONS:
  - "hour"
  - "day"
TIMESTAMP_MODE: "newest" # Change to "all" or "specific" as needed.
# If using "specific", provide a specific timestamp:
# SPECIFIC_TIMESTAMP: 1627855200000
