FILTER_IDS:
  - ["Stromerzeugung=Braunkohle", 1223]
  - ["Stromerzeugung=Kernenergie", 4068]
REGIONS:
  - "DE"
  - "AT"
RESOLUTIONS:
  - "hour"
  - "day"
TIMESTAMP_MODE: "newest" # Change to "all" or "specific" as needed.
# If using "specific", provide a specific timestamp:
# SPECIFIC_TIMESTAMP: 1627855200000
